name: medicalcenter_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  provider: ^6.1.1
  scrollable_positioned_list: ^0.3.8
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  html: ^0.15.0
  flutter_html: ^3.0.0-alpha.5
  cached_network_image: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.18.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
  assets:
    - assets/imgs/onboard-background.png
    - assets/imgs/logo-thebags.png
    - assets/imgs/logo-hive.png
    - assets/imgs/logo.png
    - assets/imgs/background-hospital.png
    - assets/imgs/profile-screen-avatar.jpg
    - assets/imgs/profile-screen-bg.png
    - assets/imgs/register-bg.png
    - assets/imgs/chat-avatar.jpeg
    - assets/imgs/argon-logo.png
    - assets/imgs/checkup_image.jpg
    - assets/imgs/service1.jpg
    - assets/imgs/service2.jpg
    - assets/imgs/service3.jpg
    - assets/imgs/service4.jpg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular-3m4L.ttf
        - asset: assets/fonts/RobotoBlack-Powx.ttf
        - asset: assets/fonts/RobotoBoldCondensed-gmVP.ttf
        - asset: assets/fonts/RobotoBoldCondensedItalic-o38a.ttf
        - asset: assets/fonts/RobotoBoldItalic-4e0x.ttf
        - asset: assets/fonts/RobotoCondensed-0GXR.ttf
        - asset: assets/fonts/RobotoItalic-W0gE.ttf
        - asset: assets/fonts/RobotoLight-aW3R.ttf
        - asset: assets/fonts/RobotoLightItalic-E9nn.ttf
        - asset: assets/fonts/RobotoMedium-Owv4.ttf
        - asset: assets/fonts/RobotoMediumItalic-ZW0m.ttf
        - asset: assets/fonts/RobotoThin-xjmK.ttf
        - asset: assets/fonts/RobotoThinItalic-pqYK.ttf

          